@extends('layouts.app')

@section('content')
@php
    $digits = preg_replace('/\D/', '', $student['phone']);
    $whatsAppPhone = '20'.ltrim(str_starts_with($digits, '20') ? substr($digits, 2) : $digits, '0');
@endphp
<section class="screen student-record" aria-labelledby="student-title">
    <header class="record-head">
        <div class="record-identity"><span class="record-avatar">{{ mb_substr($student['name'], 0, 1) }}</span><div><p class="eyebrow">ملف طالب</p><h1 id="student-title">{{ $student['name'] }}</h1><p>{{ $student['grade'] }} · {{ $student['academic_year'] }} · <span dir="ltr">{{ $student['phone'] }}</span></p></div></div>
        <div class="page-actions"><button class="outline-button" type="button" data-open-dialog="edit-student">تعديل البيانات</button><a class="primary-button" href="https://wa.me/{{ $whatsAppPhone }}" target="_blank" rel="noopener">واتساب</a></div>
    </header>
    <section class="ledger-strip"><div><span>إجمالي الرسوم</span><strong>{{ number_format($enrollments->sum('fee'), 2) }} ج.م</strong></div><div><span>إجمالي المدفوع</span><strong class="amount-ok">{{ number_format($enrollments->sum(fn ($item) => $item->payments->sum('amount')), 2) }} ج.م</strong></div><div><span>الرصيد المتبقي</span><strong class="amount-due">{{ $student['balance'] }}</strong></div></section>

    <section class="panel record-panel">
        <div class="panel-heading"><div><h2>اشتراكات الطالب</h2><span class="muted">تحصيل كل مادة وتفاصيل حسابها.</span></div>@if (auth()->user()->hasPermission('enrollments'))<button class="primary-button" type="button" data-open-dialog="add-student-subject">إضافة مادة</button>@endif</div>
        <div class="table-wrap"><table><thead><tr><th>المادة</th><th>تاريخ الاشتراك</th><th>الرسوم</th><th>الخصم</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>
            @forelse ($student['subscriptions'] as $subscription)
                <tr><td class="strong">{{ $subscription['subject'] }}<small class="table-subline">{{ $subscription['teacher'] }}</small></td><td>{{ $subscription['date'] }}</td><td>{{ $subscription['fee'] }}</td><td>{{ $subscription['discount'] }}</td><td class="amount-ok">{{ $subscription['paid'] }}</td><td class="amount-due">{{ $subscription['remaining'] }}</td><td><span class="status {{ $subscription['status'] === 'مكتمل' ? 'paid' : 'partial' }}">{{ $subscription['status'] }}</span></td><td class="table-actions">@if (auth()->user()->hasPermission('collections') && $subscription['status'] !== 'ملغى' && $subscription['raw_remaining'] > 0)<button class="chip" type="button" data-open-dialog="collect-{{ $subscription['id'] }}">تحصيل</button>@endif @if ($subscription['status'] !== 'ملغى')<button class="icon-button danger-button" type="button" data-open-dialog="cancel-{{ $subscription['id'] }}" aria-label="إلغاء الاشتراك">×</button>@endif</td></tr>
            @empty
                <tr><td colspan="8" class="muted">لا توجد مواد مسجلة لهذا الطالب بعد.</td></tr>
            @endforelse
        </tbody></table></div>
    </section>

    @foreach ($student['subscriptions'] as $subscription)
        @if ($subscription['status'] !== 'ملغى')
            <dialog id="cancel-{{ $subscription['id'] }}" class="confirm-dialog"><form method="POST" action="{{ route('enrollments.cancel', $subscription['id']) }}">@csrf<h2>إلغاء {{ $subscription['subject'] }}</h2><p>المدفوع فعليًا: {{ $subscription['paid'] }}. سجّل المبلغ المردود إن وُجد.</p><x-input label="المبلغ المردود" name="refund_amount" type="number" min="0" step="0.01" value="0" required/><div class="field-group"><label for="refund-method-{{ $subscription['id'] }}">طريقة رد المبلغ</label><select id="refund-method-{{ $subscription['id'] }}" name="refund_method"><option value="cash">نقدي</option><option value="transfer">تحويل</option><option value="wallet">محفظة</option></select></div><x-input label="ملاحظة الرد (اختياري)" name="refund_note" autocomplete="off"/><div class="dialog-actions"><button class="danger-button-text" type="submit">تأكيد الإلغاء</button><button class="chip" type="button" data-close-dialog>رجوع</button></div></form></dialog>
        @endif
        @if (auth()->user()->hasPermission('collections') && $subscription['status'] !== 'ملغى' && $subscription['raw_remaining'] > 0)
            <dialog id="collect-{{ $subscription['id'] }}" class="form-dialog"><form method="POST" action="{{ route('collections.store') }}">@csrf<input type="hidden" name="enrollment_id" value="{{ $subscription['id'] }}"><input type="hidden" name="size" value="A5"><input type="hidden" name="return_to_student" value="1"><input type="hidden" name="submission_token" value="{{ \Illuminate\Support\Str::uuid() }}"><div class="panel-heading"><div><h2>تحصيل دفعة</h2><p class="muted">{{ $subscription['subject'] }} · المتبقي {{ $subscription['remaining'] }}</p></div><button class="icon-button" type="button" data-close-dialog aria-label="إغلاق">×</button></div><div class="form-grid"><x-input label="المبلغ المستلم" name="amount" type="number" min="0.01" step="0.01" :max="$subscription['raw_remaining']" inputmode="decimal" required/><div class="field-group"><label for="collect-method-{{ $subscription['id'] }}">طريقة الدفع</label><select id="collect-method-{{ $subscription['id'] }}" name="method"><option value="cash">نقدي</option><option value="transfer">تحويل</option><option value="wallet">محفظة</option></select></div></div><div class="dialog-actions"><button class="primary-button" type="submit">تسجيل التحصيل</button><button class="chip" type="button" data-close-dialog>إلغاء</button></div></form></dialog>
        @endif
    @endforeach

    <section class="panel structured-list"><div class="panel-heading"><div><h2>مواد متاحة للطالب</h2><p class="muted">مواد الصف والسنة نفسها غير المسجل بها الطالب.</p></div>@if (auth()->user()->hasPermission('enrollments') && $availableSubjects->isNotEmpty())<button class="outline-button" type="button" data-open-dialog="add-student-subject">إضافة مادة</button>@endif</div><div class="table-wrap"><table><thead><tr><th>المادة</th><th>المدرس</th><th>قيمة الاشتراك</th></tr></thead><tbody>@forelse ($availableSubjects as $subject)<tr><td class="strong">{{ $subject->name }}</td><td>{{ $subject->teacher?->name ?? 'غير محدد' }}</td><td>{{ number_format((float) $subject->fee, 2) }} ج.م</td></tr>@empty<tr><td colspan="3" class="muted">الطالب مسجل في كل المواد المتاحة لسنة وصفه.</td></tr>@endforelse</tbody></table></div></section>
    @if (auth()->user()->hasPermission('enrollments'))
        <dialog id="add-student-subject" class="form-dialog"><form method="POST" action="{{ route('students.subjects.store', $student['id']) }}">@csrf<div class="panel-heading"><div><h2>إضافة مادة للطالب</h2><p class="muted">تُضاف للمادة المختارة من سنة وصف الطالب.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="إغلاق">×</button></div><div class="form-grid"><div class="field-group"><label for="student-subject">المادة</label><select id="student-subject" name="subject_id" required><option value="">اختر المادة…</option>@foreach ($availableSubjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }} — {{ number_format($subject->fee, 2) }} ج.م</option>@endforeach</select></div><x-input label="المدفوع الآن" name="paid_amount" type="number" min="0" step="0.01" value="0" inputmode="decimal" required/><div class="field-group"><label for="student-payment-method">طريقة الدفع</label><select id="student-payment-method" name="payment_method"><option value="cash">نقدي</option><option value="transfer">تحويل</option><option value="wallet">محفظة</option></select></div><div class="field-group"><label for="student-discount-type">نوع الخصم</label><select id="student-discount-type" name="discount_type"><option value="">لا يوجد</option><option value="amount">مبلغ</option><option value="percentage">نسبة</option></select></div><x-input label="قيمة الخصم" name="discount_value" type="number" min="0" step="0.01" value="0" inputmode="decimal"/><x-input label="سبب الخصم (اختياري)" name="reason"/></div><div class="dialog-actions"><button class="primary-button" type="submit">إضافة المادة</button><button class="chip" type="button" data-close-dialog>إلغاء</button></div></form></dialog>
    @endif
    @if (auth()->user()->hasPermission('discounts'))
        <section class="panel discount-inline"><div><h2>خصم على اشتراك</h2><p>اختر المادة ثم أدخل قيمة الخصم وسببه.</p></div><form method="POST" action="{{ route('discounts.store') }}">@csrf<input type="hidden" name="return_to_student" value="1"><div class="form-grid"><div class="field-group"><label for="discount-enrollment">المادة</label><select id="discount-enrollment" name="enrollment_id" required>@foreach ($enrollments->whereNull('cancelled_at') as $enrollment)<option value="{{ $enrollment->id }}">{{ $enrollment->subject->name }} · المتبقي {{ number_format(max(0, $enrollment->fee - $enrollment->discount_amount - $enrollment->payments->sum('amount')), 2) }} ج.م</option>@endforeach</select></div><div class="field-group"><label for="discount-type">نوع الخصم</label><select id="discount-type" name="type"><option value="amount">مبلغ</option><option value="percentage">نسبة مئوية</option></select></div><x-input label="قيمة الخصم" name="value" type="number" min="0.01" step="0.01" required/><x-input label="سبب الخصم" name="reason" placeholder="مثال: خصم أخوات" required/></div><button class="primary-button form-save" type="submit">اعتماد الخصم</button></form></section>
    @endif
    <section class="panel structured-list"><div class="panel-heading"><h2>سجل المبالغ المردودة</h2><span class="muted">تظهر أيضًا ضمن تقرير الحركات المالية.</span></div><div class="table-wrap"><table><thead><tr><th>المادة</th><th>المبلغ</th><th>الطريقة</th><th>التاريخ</th><th>المنفذ</th><th>ملاحظة</th></tr></thead><tbody>@forelse ($refunds as $refund)<tr><td class="strong">{{ $refund->enrollment->subject->name }}</td><td class="amount-due">{{ number_format($refund->amount, 2) }} ج.م</td><td>{{ ['cash' => 'نقدي', 'transfer' => 'تحويل', 'wallet' => 'محفظة'][$refund->method] }}</td><td>{{ $refund->refunded_at->translatedFormat('j F Y') }}</td><td>{{ $refund->processor->name }}</td><td>{{ $refund->note ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="muted">لا توجد مبالغ مردودة لهذا الطالب.</td></tr>@endforelse</tbody></table></div></section>
    <dialog id="edit-student" class="form-dialog" @if (request()->boolean('edit')) data-auto-dialog @endif><form method="POST" action="{{ route('students.update', $student['id']) }}">@csrf @method('PUT')<div class="panel-heading"><h2>تعديل بيانات الطالب</h2><button class="icon-button" type="button" data-close-dialog aria-label="إغلاق">×</button></div><div class="form-grid"><x-input label="اسم الطالب" name="name" :value="$student['name']" required/><x-input label="رقم الهاتف" name="phone" type="tel" :value="$student['phone']" required/><x-input label="اسم ولي الأمر" name="guardian_name" :value="$student['guardian_name']"/><x-input label="هاتف ولي الأمر" name="guardian_phone" type="tel" :value="$student['guardian_phone']"/></div><div class="form-field"><label for="student-note">ملاحظات الطالب</label><textarea id="student-note" name="note" rows="3">{{ $student['note'] }}</textarea></div><div class="dialog-actions"><button class="primary-button" type="submit">حفظ التعديل</button><button class="chip" type="button" data-close-dialog>إلغاء</button></div></form></dialog>
    @if ($completedPayment)
        @php($paymentMessage = 'تم استلام '.number_format((float) $completedPayment->amount, 2).' ج.م من '.$completedPayment->student->name.' لحساب مادة '.$completedPayment->enrollment->subject->name.'. رقم الوصل: '.$completedPayment->receipt_number)
        <dialog class="success-dialog" data-auto-dialog aria-labelledby="student-collection-success"><div class="success-mark">✓</div><h2 id="student-collection-success">تم التحصيل بنجاح</h2><p>{{ $paymentMessage }}</p><div class="dialog-actions"><a class="primary-button" href="{{ route('receipts.show', ['payment' => $completedPayment, 'size' => request()->query('size', 'A5')]) }}" target="_blank">طباعة الوصل</a><a class="outline-button" href="https://wa.me/{{ $whatsAppPhone }}?text={{ urlencode($paymentMessage) }}" target="_blank" rel="noopener">إرسال واتساب</a><button class="chip" type="button" data-close-dialog>إغلاق</button></div></dialog>
    @endif
</section>
@endsection
