@extends('layouts.app')

@section('content')
<section class="screen teacher-record" aria-labelledby="teacher-title">
<header class="record-head"><div class="record-identity"><span class="record-avatar">{{ mb_substr($teacher->name, 0, 1) }}</span><div><p class="eyebrow">ملف مدرس</p><h1 id="teacher-title">{{ $teacher->name }}</h1><p dir="ltr">{{ $teacher->phone ?: 'لم يُسجل رقم هاتف' }}</p></div></div><div class="page-actions"><a class="outline-button" href="{{ route('teachers.index') }}">العودة للمدرسين</a><a class="primary-button" href="{{ route('teacher-payouts.index', ['teacher' => $teacher->id]) }}">صرف مستحقات</a></div></header>
<section class="ledger-strip teacher-wallet"><div><span>تحصيل مواد المدرس</span><strong class="amount-ok">{{ number_format($collections, 2) }} ج.م</strong></div><div><span>ديون الطلاب الحالية</span><strong class="amount-due">{{ number_format($due, 2) }} ج.م</strong></div><div><span>ما تم صرفه</span><strong>{{ number_format($payoutTotal, 2) }} ج.م</strong></div><div><span>مستحقات تحت التسوية</span><strong>{{ number_format($collections - $payoutTotal, 2) }} ج.م</strong></div></section>
<section class="panel record-panel"><div class="panel-heading"><h2>محافظ المواد</h2><span class="muted">التحصيل الفعلي والديون لكل مادة.</span></div><div class="table-wrap"><table><thead><tr><th>المادة</th><th>عدد الطلاب</th><th>داخل المحفظة</th><th>ديون خارجية</th></tr></thead><tbody>@forelse($subjects as $subject)<tr><td class="strong">{{ $subject['name'] }}</td><td>{{ $subject['students'] }}</td><td class="amount-ok">{{ number_format($subject['paid'], 2) }} ج.م</td><td class="amount-due">{{ number_format($subject['due'], 2) }} ج.م</td></tr>@empty<tr><td colspan="4" class="muted">لا توجد مواد مرتبطة بالمدرس.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel structured-list"><div class="panel-heading"><h2>سجل الصرف</h2></div><div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>المبلغ</th><th>الطريقة</th><th>ملاحظة</th></tr></thead><tbody>@forelse($teacher->payouts as $payout)<tr><td dir="ltr">{{ \App\Support\DatePresenter::date($payout->paid_at) }}</td><td class="amount-due">{{ number_format($payout->amount, 2) }} ج.م</td><td>{{ ['cash'=>'نقدي','transfer'=>'تحويل','wallet'=>'محفظة'][$payout->method] }}</td><td>{{ $payout->note ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="muted">لم يُسجل أي صرف لهذا المدرس بعد.</td></tr>@endforelse</tbody></table></div></section>
</section>
@endsection
